### ISSUE TITLE
Google Chat Smiley's

### ISSUE THREAD

**Issue by tupson** [EionRobb/purple-googlechat#25]
I have noticed when I use the Google Chat .dll versus the XMPP for my Gmail Account, most of the emoji's vanish, limiting them to 16 smiley's in total.

How can I get all of the emoji's to function that are within the "C:\Program Files (x86)\Pidgin\pixmaps\pidgin\emotes\default" directory?

It would also appear most of all the icons within C:\Program Files (x86)\Pidgin\pixmaps\ aren't referenced.

![icons](https://user-images.githubusercontent.com/45882413/135101028-ec44827c-6eef-4c8e-a51c-eea5f7f9b31d.png)

**Comment by EionRobb** [comment]
So a protocol plugin can't influence what shows in the smileys list, its up to the smiley theme to optionally read in the name of the protocol.  That's because a protocol plugin works independently of the UI - the same plugin works with Adium, spectrum2, bitlbee and Finch; all of which use a different smiley theme system.

To resolve, you'd either need to edit the `theme` file in `Pidgin\pixmaps\pidgin\emotes\default` to reference both "Google Chat" as well as "XMPP", or switch to a different smiley theme (I personally use https://github.com/niclashoyer/pidgin-emojione ) which doesn't have protocol-specific smileys

**Comment by EionRobb** [comment]
Glad to hear it :)
